security:
  basic:
    enabled: false

management:
  security:
    enabled: false

logging:
  level:
    io:
      pivotal: DEBUG

greeting:
  displayFortune: true

SPRING_PROFILES_ACTIVE=qa ./mvnw clean spring-boot:run

quoteServiceURL: http://quote-service-qa-solstice.cfapps.io/quote

